name: Publish canary branch

on:
  push:
    branches-ignore:
      - master
      - dev

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    permissions: write-all
    if: contains(github.ref_name, 'canary')
    steps:
      - name: 'Checkout' # Download code from the repository
        uses: actions/checkout@v2 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: 'Use NodeJS 18' # Setup node using version 14
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: '18.17.0'

      - name: 'Setup lerna@6.6.1'
        run: yarn global add lerna@6.6.1  --ignore-engines

      - name: Set up Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build dependencies
        run: |
          lerna clean --yes
          node etc/bootstrapEnv
          yarn install  --ignore-engines
          yarn build

      - name: 'Setup npm'
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          lerna version prerelease --preid alpha --force-git-tag --no-changelog --yes
          lerna publish from-git --force-git-tag --dist-tag alpha --yes --summary-file

      - name: 'Broadcast published versions on Slack'
        run: node etc/slack --api=$SLACK_API --actor=$GIT_ACTOR --commit-message=$GIT_LATEST_COMMIT_MESSAGE
        env:
          GIT_ACTOR: ${{ github.actor }}
          SLACK_API: ${{ secrets.SLACK_API }}
          GIT_LATEST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
